spring:
  security:
    oauth2:
      client:
        provider:
          api-gateway-service:
            issuer-uri: http://localhost:8080/realms/feing
        registration:
          api-gateway-service:
            provider: api-gateway-service
            client-id: api-gateway-client
            client-secret: eroDngoLvD1e3Zobh66uIZuMTkhJDsG4
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
  application:
    name: gateway

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: users-service
          uri: http://localhost:8084
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0


server:
  port: 9090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}


#spring.cloud.gateway.routes[0].filters=StripPrefix=2